# Generated by Django 4.2.4 on 2023-09-09 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PCAPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("file", models.FileField(upload_to="pcap_files/")),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("dst_ip_address", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField()),
                ("protocol", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("http_request", models.TextField(blank=True, null=True)),
                ("http_response", models.TextField(blank=True, null=True)),
                ("dns_info", models.TextField(blank=True, null=True)),
                ("other_info", models.TextField(blank=True, null=True)),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcap_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pcapfile",
                    ),
                ),
            ],
        ),
    ]
