# Generated by Django 4.2.4 on 2023-09-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_networkpacket_is_brute_force_networkpacket_is_dos_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="networkpacket",
            old_name="http_request",
            new_name="request_uri",
        ),
        migrations.RemoveField(
            model_name="networkpacket",
            name="http_response",
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="referer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="request_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="response_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="response_version",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="source_port",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="networkpacket",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
