# Generated by Django 4.2.5 on 2023-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_pcapfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkpacket",
            name="task_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
