# Generated by Django 4.2.5 on 2023-10-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_networkpacket_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkpacket",
            name="task_id",
        ),
        migrations.AddField(
            model_name="pcapfile",
            name="task_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
